[package]
name = "infotainer"
version = "0.1.0"
authors = ["joppich <joppich@bricknet.de>"]

[[bin]]
name = "infotainer"
path = "src/main.rs"

[dependencies]
env_logger = "0.6"
futures = "0.1"
actix = "0.8"
actix-web = "1.0"
