[package]
name = "infotainer"
version = "0.1.0"
authors = ["joppich <joppich@bricknet.de>"]
edition = "2018"

[[bin]]
name = "infotainer"
path = "src/main.rs"

[dependencies]
log = "0.4.0"
env_logger = "0.7.1"
futures = "0.3.1"
actix = "0.9"
actix-codec = "0.2"
actix-web = "2.0"
actix-web-actors = "2.0"
actix-files = "0.2.1"
actix-rt = "1.0"
awc = "1.0"
serde = { version="1.0", features = ["derive"] }
serde_json = "1.0"
