name: Rust
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  CARGO_TERM_COLOR: always
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install tarpaulin
      run: cargo install cargo-tarpaulin
    - name: Run tests
      run: cargo tarpaulin --verbose --all-features --workspace --timeout 120 --out Xml
    - name: Upload coverage stats
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
